blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/NasiMA-MyLife/awesome-python-applications/discussions
    about: Ask questions and share ideas here
